-- =============================================================================
-- YouTogether — Database Initialization Script
-- =============================================================================
-- Project      : YouTogether (Watch Party Platform)
-- Description  : PostgreSQL schema initialization for the YouTogether MVP.
--                Implements the domain model defined in the Data Model
--                Specification (RNCP39583 — Bloc 2: C2.2.1, C2.2.2, C2.2.3).
-- Architecture : Clean Architecture / Domain-Driven Design
-- Backend      : NestJS with TypeORM
-- DBMS         : PostgreSQL 15+
-- Language     : English (code, comments, documentation)
-- Version      : 1.0.0
-- =============================================================================
-- Usage:
--   psql -U <user> -d <database> -f init.sql
--   or via Docker:
--   docker exec -i <container> psql -U <user> -d <database> < init.sql
-- =============================================================================


-- -----------------------------------------------------------------------------
-- EXTENSIONS
-- Enables UUID generation natively within PostgreSQL.
-- pgcrypto is used as a fallback; uuid-ossp is the primary extension.
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- -----------------------------------------------------------------------------
-- CLEANUP (idempotent re-run safety)
-- Drop tables in reverse dependency order to avoid FK constraint violations.
-- Drop types last as tables depend on them.
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS video_sessions     CASCADE;
DROP TABLE IF EXISTS room_memberships   CASCADE;
DROP TABLE IF EXISTS rooms              CASCADE;
DROP TABLE IF EXISTS users              CASCADE;

DROP TYPE IF EXISTS user_role;


-- =============================================================================
-- TYPES
-- =============================================================================

-- user_role ENUM
-- Represents the authorisation level of a user within the application.
--   registered : authenticated user — may create/join rooms and control playback
--                if designated as room leader.
--   guest      : unauthenticated visitor — read-only access, no playback control.
CREATE TYPE user_role AS ENUM ('registered', 'guest');


-- =============================================================================
-- TABLE: users
-- =============================================================================
-- Domain aggregate root for the identity and authentication sub-domain.
-- Passwords are stored as bcrypt hashes; plain-text credentials are never
-- persisted (OWASP A02 — Cryptographic Failures).
-- Soft deletion is used to preserve referential integrity with historical
-- membership and session records (OWASP A09 — Security Logging / Audit Trail).
-- =============================================================================

CREATE TABLE users (
    -- Primary key: UUID v4 generated by PostgreSQL.
    id                  UUID            NOT NULL DEFAULT uuid_generate_v4(),

    -- User email address. Used as the unique login credential.
    -- Stored normalised to lowercase at the application layer before insertion.
    -- Maximum length follows RFC 5322: 255 characters.
    email               VARCHAR(255)    NOT NULL,

    -- Bcrypt hash of the user password (cost factor >= 12 recommended).
    -- Never store plain-text or reversibly encrypted passwords.
    password_hash       VARCHAR(255)    NOT NULL,

    -- Display name rendered in the room UI.
    username            VARCHAR(50)     NOT NULL,

    -- Authorisation role. Defaults to 'registered' for all newly created accounts.
    -- The 'guest' role is assigned programmatically to anonymous sessions.
    role                user_role       NOT NULL DEFAULT 'registered',

    -- Hash of the current OAuth2 refresh token (Google OAuth2 flow).
    -- NULL when no active session exists (e.g., after logout).
    -- Storing the hash prevents token replay if the database is compromised
    -- (OWASP A07 — Identification and Authentication Failures).
    refresh_token_hash  VARCHAR(255)    NULL,

    -- Audit timestamps. Both are managed at the application layer (TypeORM
    -- subscribers or lifecycle hooks) and should never be set manually via SQL
    -- during normal operation.
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Soft-delete timestamp. NULL indicates the account is active.
    -- A non-NULL value logically removes the user from the system without
    -- breaking existing foreign key references.
    deleted_at          TIMESTAMPTZ     NULL,

    -- -------------------------------------------------------------------------
    -- CONSTRAINTS
    -- -------------------------------------------------------------------------
    CONSTRAINT pk_users
        PRIMARY KEY (id),

    -- Email uniqueness is enforced only among non-deleted users.
    -- The partial unique index below handles this case; the constraint here
    -- ensures no two active accounts share an email.
    CONSTRAINT uq_users_email
        UNIQUE (email)
);

-- Partial unique index: enforce email uniqueness only for active (non-deleted) users.
-- This allows the same email to be re-used after soft deletion if required.
CREATE UNIQUE INDEX uix_users_email_active
    ON users (email)
    WHERE deleted_at IS NULL;

-- Index: accelerate lookup by email during authentication.
CREATE INDEX ix_users_email
    ON users (email);

-- Index: filter active users efficiently.
CREATE INDEX ix_users_deleted_at
    ON users (deleted_at)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE  users                    IS 'Domain aggregate root for user identity and authentication. Passwords stored as bcrypt hashes. Soft-delete pattern preserves referential integrity.';
COMMENT ON COLUMN users.id                 IS 'UUID v4 primary key, generated by PostgreSQL.';
COMMENT ON COLUMN users.email              IS 'Unique login email, normalised to lowercase. RFC 5322 compliant, max 255 chars.';
COMMENT ON COLUMN users.password_hash      IS 'Bcrypt hash of the user password. Cost factor >= 12. Never plain-text.';
COMMENT ON COLUMN users.username           IS 'Display name rendered in the room UI. Max 50 chars.';
COMMENT ON COLUMN users.role               IS 'Authorisation role: registered (authenticated) or guest (anonymous, read-only).';
COMMENT ON COLUMN users.refresh_token_hash IS 'Hash of the current OAuth2 refresh token. NULL when no active session exists.';
COMMENT ON COLUMN users.created_at         IS 'Account creation timestamp (UTC).';
COMMENT ON COLUMN users.updated_at         IS 'Last profile update timestamp (UTC). Maintained by application layer.';
COMMENT ON COLUMN users.deleted_at         IS 'Soft-delete timestamp. NULL = active account.';


-- =============================================================================
-- TABLE: rooms
-- =============================================================================
-- Domain aggregate root for the broadcast group sub-domain.
-- The room creator is automatically the owner (leader) for the MVP.
-- No advanced role system is implemented at this stage.
-- Only the owner may update or delete their room.
-- Soft deletion is used for consistency with the user table.
-- =============================================================================

CREATE TABLE rooms (
    -- Primary key: UUID v4.
    id              UUID            NOT NULL DEFAULT uuid_generate_v4(),

    -- Human-readable public name of the room.
    -- Must be non-empty; max 100 characters enforced by the domain layer
    -- and the check constraint below.
    name            VARCHAR(100)    NOT NULL,

    -- Optional description providing context about the room's purpose.
    description     TEXT            NULL,

    -- Foreign key to the user who created the room.
    -- This user is the sole administrator (leader) for the MVP.
    -- ON DELETE RESTRICT prevents accidental cascade deletion of rooms
    -- when a user account is soft-deleted; the application layer must
    -- handle this scenario explicitly.
    owner_id        UUID            NOT NULL,

    -- Visibility flag. TRUE = room appears in the public listing.
    -- All rooms are public by default for the MVP.
    is_public       BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Audit timestamps.
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Soft-delete timestamp. NULL = room is active.
    deleted_at      TIMESTAMPTZ     NULL,

    -- -------------------------------------------------------------------------
    -- CONSTRAINTS
    -- -------------------------------------------------------------------------
    CONSTRAINT pk_rooms
        PRIMARY KEY (id),

    CONSTRAINT fk_rooms_owner
        FOREIGN KEY (owner_id) REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Room name must not be blank.
    CONSTRAINT chk_rooms_name_not_empty
        CHECK (TRIM(name) <> '')
);

-- Index: list rooms by owner.
CREATE INDEX ix_rooms_owner_id
    ON rooms (owner_id);

-- Index: filter public, active rooms for the listing feature.
CREATE INDEX ix_rooms_public_active
    ON rooms (is_public, deleted_at)
    WHERE is_public = TRUE AND deleted_at IS NULL;

-- Index: soft-delete filter.
CREATE INDEX ix_rooms_deleted_at
    ON rooms (deleted_at)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE  rooms             IS 'Domain aggregate root for broadcast groups (rooms). Owner is the sole administrator in the MVP. Soft-delete pattern used.';
COMMENT ON COLUMN rooms.id          IS 'UUID v4 primary key.';
COMMENT ON COLUMN rooms.name        IS 'Public display name. Non-empty, max 100 chars.';
COMMENT ON COLUMN rooms.description IS 'Optional room description. No length constraint at DB level.';
COMMENT ON COLUMN rooms.owner_id    IS 'FK → users.id. Room creator and sole leader.';
COMMENT ON COLUMN rooms.is_public   IS 'TRUE = visible in the public room listing.';
COMMENT ON COLUMN rooms.created_at  IS 'Room creation timestamp (UTC).';
COMMENT ON COLUMN rooms.updated_at  IS 'Last update timestamp (UTC). Maintained by application layer.';
COMMENT ON COLUMN rooms.deleted_at  IS 'Soft-delete timestamp. NULL = active room.';


-- =============================================================================
-- TABLE: room_memberships
-- =============================================================================
-- Tracks which registered users have joined a room.
-- Child entity within the Room aggregate boundary.
-- A user may only hold one active membership per room at a given time.
-- left_at is set when a user leaves; a new row is inserted upon re-joining,
-- preserving the full participation history.
-- =============================================================================

CREATE TABLE room_memberships (
    -- Primary key: UUID v4.
    id          UUID        NOT NULL DEFAULT uuid_generate_v4(),

    -- The room this membership belongs to.
    room_id     UUID        NOT NULL,

    -- The member user.
    user_id     UUID        NOT NULL,

    -- Timestamp of the join action.
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Timestamp when the user left the room.
    -- NULL indicates the membership is currently active.
    left_at     TIMESTAMPTZ NULL,

    -- -------------------------------------------------------------------------
    -- CONSTRAINTS
    -- -------------------------------------------------------------------------
    CONSTRAINT pk_room_memberships
        PRIMARY KEY (id),

    CONSTRAINT fk_room_memberships_room
        FOREIGN KEY (room_id) REFERENCES rooms (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_room_memberships_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- A user may only have one active membership per room at a time.
    -- "Active" is defined as left_at IS NULL.
    -- This partial unique index enforces the invariant at the database level.
    CONSTRAINT chk_room_memberships_dates
        CHECK (left_at IS NULL OR left_at >= joined_at)
);

-- Partial unique index: one active membership per user per room.
CREATE UNIQUE INDEX uix_room_memberships_active
    ON room_memberships (room_id, user_id)
    WHERE left_at IS NULL;

-- Index: retrieve all members of a room.
CREATE INDEX ix_room_memberships_room_id
    ON room_memberships (room_id);

-- Index: retrieve all rooms a user is a member of.
CREATE INDEX ix_room_memberships_user_id
    ON room_memberships (user_id);

COMMENT ON TABLE  room_memberships           IS 'Tracks user participation in rooms. Child entity within the Room aggregate. Preserves full join/leave history.';
COMMENT ON COLUMN room_memberships.id        IS 'UUID v4 primary key.';
COMMENT ON COLUMN room_memberships.room_id   IS 'FK → rooms.id. The room this membership belongs to.';
COMMENT ON COLUMN room_memberships.user_id   IS 'FK → users.id. The participating user.';
COMMENT ON COLUMN room_memberships.joined_at IS 'Timestamp of the join action (UTC).';
COMMENT ON COLUMN room_memberships.left_at   IS 'Timestamp of departure (UTC). NULL = currently active member.';


-- =============================================================================
-- TABLE: video_sessions
-- =============================================================================
-- Represents a YouTube video queued or actively playing in a room.
-- YouTube metadata (title, thumbnail, duration) is cached at insertion time
-- to reduce API call volume and ensure display consistency regardless of
-- YouTube API availability.
-- Only the room owner (leader) may create a VideoSession for the MVP.
-- =============================================================================

CREATE TABLE video_sessions (
    -- Primary key: UUID v4.
    id                  UUID            NOT NULL DEFAULT uuid_generate_v4(),

    -- The room in which this video session is associated.
    room_id             UUID            NOT NULL,

    -- YouTube video identifier — 11 alphanumeric characters.
    -- Format validated at the application layer (YouTubeVideoId value object).
    youtube_video_id    VARCHAR(20)     NOT NULL,

    -- Video title cached from the YouTube Data API v3 at insertion time.
    title               VARCHAR(255)    NOT NULL,

    -- Thumbnail URL cached from the YouTube Data API v3.
    -- NULL if the thumbnail is unavailable at insertion time.
    thumbnail_url       VARCHAR(512)    NULL,

    -- Total video duration in seconds. Used to validate seek operations
    -- (PlaybackTimestamp value object invariant: 0 <= seconds <= duration_seconds).
    duration_seconds    INTEGER         NOT NULL,

    -- The user who added this video session. Must be the room owner for the MVP.
    added_by            UUID            NOT NULL,

    -- Creation timestamp.
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- -------------------------------------------------------------------------
    -- CONSTRAINTS
    -- -------------------------------------------------------------------------
    CONSTRAINT pk_video_sessions
        PRIMARY KEY (id),

    CONSTRAINT fk_video_sessions_room
        FOREIGN KEY (room_id) REFERENCES rooms (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_video_sessions_added_by
        FOREIGN KEY (added_by) REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    -- Duration must be a positive integer.
    CONSTRAINT chk_video_sessions_duration
        CHECK (duration_seconds > 0),

    -- YouTube video ID format: exactly 11 characters, alphanumeric plus - and _.
    CONSTRAINT chk_video_sessions_youtube_id_format
        CHECK (youtube_video_id ~ '^[A-Za-z0-9_\-]{11}$')
);

-- Index: retrieve all video sessions for a room.
CREATE INDEX ix_video_sessions_room_id
    ON video_sessions (room_id);

-- Index: retrieve sessions added by a specific user.
CREATE INDEX ix_video_sessions_added_by
    ON video_sessions (added_by);

-- Index: look up a session by YouTube video ID within a room.
CREATE INDEX ix_video_sessions_youtube_id
    ON video_sessions (room_id, youtube_video_id);

COMMENT ON TABLE  video_sessions                    IS 'YouTube video sessions associated with a room. Metadata is cached from the YouTube Data API v3 at insertion. Duration enables seek validation.';
COMMENT ON COLUMN video_sessions.id                 IS 'UUID v4 primary key.';
COMMENT ON COLUMN video_sessions.room_id            IS 'FK → rooms.id. The room this session belongs to.';
COMMENT ON COLUMN video_sessions.youtube_video_id   IS '11-character YouTube video identifier (e.g. dQw4w9WgXcQ).';
COMMENT ON COLUMN video_sessions.title              IS 'Video title cached from YouTube Data API v3 at insertion time.';
COMMENT ON COLUMN video_sessions.thumbnail_url      IS 'Thumbnail URL cached from YouTube Data API v3. May be NULL.';
COMMENT ON COLUMN video_sessions.duration_seconds   IS 'Total video duration in seconds. Must be > 0. Used to validate seek operations.';
COMMENT ON COLUMN video_sessions.added_by           IS 'FK → users.id. The room owner who initiated the session.';
COMMENT ON COLUMN video_sessions.created_at         IS 'Session creation timestamp (UTC).';


-- =============================================================================
-- TRIGGER: auto-update updated_at
-- =============================================================================
-- Automatically refreshes the updated_at column on UPDATE for tables that
-- carry this column. This removes the responsibility from the application layer
-- and guarantees consistency even for direct database modifications.
-- =============================================================================

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_set_updated_at IS 'Trigger function: automatically sets updated_at = NOW() on any UPDATE operation.';

-- Attach trigger to users table.
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();

-- Attach trigger to rooms table.
CREATE TRIGGER trg_rooms_updated_at
    BEFORE UPDATE ON rooms
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_updated_at();


-- =============================================================================
-- SEED DATA (development environment only)
-- =============================================================================
-- Remove or comment out this section before applying to staging or production.
-- Passwords below are bcrypt hashes of the string "Password1!" (cost 12).
-- DO NOT use these credentials in any environment other than local development.
-- =============================================================================

-- Development seed: administrator user (room owner)
INSERT INTO users (id, email, password_hash, username, role)
VALUES (
    'a0000000-0000-0000-0000-000000000001',
    'admin@youtogether.dev',
    '$2b$12$examplehashfortestingonlyAAAAAAAAAAAAAAAAAAAAAAAAAA',  -- replace with real bcrypt hash
    'AdminDev',
    'registered'
);

-- Development seed: standard registered user
INSERT INTO users (id, email, password_hash, username, role)
VALUES (
    'a0000000-0000-0000-0000-000000000002',
    'user@youtogether.dev',
    '$2b$12$examplehashfortestingonlyBBBBBBBBBBBBBBBBBBBBBBBBB',  -- replace with real bcrypt hash
    'UserDev',
    'registered'
);

-- Development seed: public room owned by the admin user
INSERT INTO rooms (id, name, description, owner_id, is_public)
VALUES (
    'b0000000-0000-0000-0000-000000000001',
    'Dev Room Alpha',
    'Default development room for integration testing.',
    'a0000000-0000-0000-0000-000000000001',
    TRUE
);

-- Development seed: membership — admin is a member of their own room
INSERT INTO room_memberships (room_id, user_id)
VALUES (
    'b0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000001'
);

-- Development seed: membership — standard user joins the room
INSERT INTO room_memberships (room_id, user_id)
VALUES (
    'b0000000-0000-0000-0000-000000000001',
    'a0000000-0000-0000-0000-000000000002'
);

-- Development seed: a video session in the dev room
INSERT INTO video_sessions (room_id, youtube_video_id, title, thumbnail_url, duration_seconds, added_by)
VALUES (
    'b0000000-0000-0000-0000-000000000001',
    'dQw4w9WgXcQ',
    'Rick Astley — Never Gonna Give You Up',
    'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    212,
    'a0000000-0000-0000-0000-000000000001'
);


-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================
-- Run these queries after initialization to verify the schema is correct.
-- Expected output is documented inline.
-- =============================================================================

-- List all tables created in the public schema.
-- Expected: users, rooms, room_memberships, video_sessions
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- List all indexes.
SELECT indexname, tablename, indexdef
FROM pg_indexes
WHERE schemaname = 'public'
ORDER BY tablename, indexname;

-- Count seed rows.
-- Expected: users=2, rooms=1, room_memberships=2, video_sessions=1
SELECT 'users'            AS entity, COUNT(*) AS row_count FROM users
UNION ALL
SELECT 'rooms',            COUNT(*) FROM rooms
UNION ALL
SELECT 'room_memberships', COUNT(*) FROM room_memberships
UNION ALL
SELECT 'video_sessions',   COUNT(*) FROM video_sessions;
